spring.application.name=weather
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jooq.sql-dialect=POSTGRES
spring.jooq.render-name-case=lower_if_unquoted

# Redis Upstash
spring.data.redis.host=${UPSTASH_REDIS_HOST}
spring.data.redis.port=${UPSTASH_REDIS_PORT}
spring.data.redis.password=${UPSTASH_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true

# Cache
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000