spring:
  datasource:
    url: ${DB_URL}?currentSchema=meteo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
  cache:
    type: redis
  data:
    redis:
      host: ${UPSTASH_REDIS_HOST}
      port: ${UPSTASH_REDIS_PORT:6379}
      password: ${UPSTASH_REDIS_PASSWORD}
      ssl:
        enabled: true

server:
  port: 8081

meteo:
  openmeteo:
    base-url: https://api.open-meteo.com/v1
    base-url-historico: https://archive-api.open-meteo.com/v1
    forecast-days: 15
    paso-malla: 0.25
  jobs:
    forecast-cron: "0 0 */6 * * *"
    current-cron: "0 0 * * * *"
    historical-cron: "0 30 3 * * *"

logging:
  level:
    com.meteo: DEBUG